apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    cluster: management
  name: authx-scylla
  namespace: nalej
data:
  authx-scylla.cql: |
    create KEYSPACE IF NOT EXISTS authx WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};
    create table authx.credentials (username text, password blob, role_id text, organization_id text, PRIMARY KEY (username));
    create table authx.roles (organization_id text, role_id text, name text, internal boolean, primitives list<text>, PRIMARY KEY (organization_id, role_id));
    create table authx.tokens (username text, token_id text, refresh_token blob, expiration_date bigint, PRIMARY KEY (username, token_id));
  node_alive.sh: |
    #!/bin/bash
    echo 'executing script...'
    KEYSPACE=$(cqlsh scylladb -e "DESCRIBE KEYSPACES") 2> dev/null
    while [ $? -ne 0 ]
    do
      echo 'sleep 1'
      sleep 1
      KEYSPACES=$(cqlsh scylladb -e "DESCRIBE KEYSPACES") 2> dev/null
    done
    echo 'creating database...'
    cqlsh scylladb -f /opt/authx-scylla.cql

    exit;