kind: Service
apiVersion: v1
metadata:
  name: authx
  labels:
    cluster: management
    compoment: authx
  namespace: __NPH_NAMESPACE
spec:
  selector:
    cluster: management
    component: authx
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8810
    targetPort: 8810
