kind: Service
apiVersion: v1
metadata:
  name: authx
  labels:
    cluster: management
    compoment: authx
  namespace: nalej
spec:
  selector:
    cluster: management
    component: authx
  type: NodePort
  ports:
  - protocol: TCP
    port: 8810
    targetPort: 8810
    nodePort: 31810