###
# AUTHX
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: authx
  name: authx
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: authx
  template:
    metadata:
      labels:
        cluster: management
        component: authx
    spec:
      containers:
      - name: authx
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/authx:__NPH_VERSION
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--secret=/etc/authx/secret"
        - "--debug"
        - "--useDBScyllaProviders=true"
        - "--scyllaDBAddress=scylladb.__NPH_NAMESPACE"
        - "--scyllaDBKeyspace=authx"
        - "--scyllaDBPort=9042"
        volumeMounts:
        - name: authx-secret-volume
          mountPath: "/etc/authx"
          readOnly: true
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
      volumes:
      - name: authx-secret-volume
        secret:
          secretName: authx-secret
