[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.9.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/nalej/grpc-authx-go"
  version = "0.0.2"

[[constraint]]
  name = "github.com/nalej/derrors"
  version = "1.1.1"
[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"
[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"
[prune]
  go-tests = true
  unused-packages = true


